apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reactProject
  annotations:
    github.com/project-slug: e1-mslee/reactProject
spec:
  type: other
  lifecycle: unknown
  owner: guests
