CREATE TABLE STD_MAIN (
    TABLE_SEQ INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TABLE_NAME VARCHAR(100),
    TABLE_ID VARCHAR(10),
    VBG_CRE_USER VARCHAR(50),
    VBG_CRE_DTM DATE
);

CREATE TABLE STD_FIELD (
    TABLE_SEQ INT(3) NOT NULL,
    COL_ID VARCHAR(10) NOT NULL,
    COL_NAME VARCHAR(100),
    COL_TYPE VARCHAR(1),
    COL_SIZE INT(5),
    COL_IDX VARCHAR(1),
    COL_SCH VARCHAR(1),
    VBG_CRE_USER VARCHAR(50),
    VBG_CRE_DTM DATE,
    PRIMARY KEY (TABLE_SEQ, COL_ID)
);


CREATE TABLE COMM_CODE (
    COM_CD_ID VARCHAR(10),
    COM_CD VARCHAR(1),
    COM_CD_NM VARCHAR(100),
    COM_CD_EN VARCHAR(10),
    SORT_SN INT(2),
    VBG_CRE_USER VARCHAR(50),
    VBG_CRE_DTM DATE,
    PRIMARY KEY (COM_CD_ID, COM_CD)
);

CREATE TABLE STD_HEADER (
    TABLE_SEQ INT(3) ,
    HEADER_ID VARCHAR(10),
    HEADER_NAME VARCHAR(10),
    SUPI_HEADER VARCHAR(10),
    HEADER_WIDTH INT,
    CONN_FIELD VARCHAR(10),
    SORT_SN INT(2),
    PRIMARY KEY (HEADER_ID, TABLE_SEQ)
);

INSERT INTO uda.comm_code
(COM_CD_ID, COM_CD, COM_CD_NM, COM_CD_EN, SORT_SN, VBG_CRE_USER, VBG_CRE_DTM)
VALUES('00001', '1', '숫자', 'int', 1, 'LMS', '2025-07-15');
INSERT INTO uda.comm_code
(COM_CD_ID, COM_CD, COM_CD_NM, COM_CD_EN, SORT_SN, VBG_CRE_USER, VBG_CRE_DTM)
VALUES('00001', '2', '긴문자열', 'VARCHAR', 2, 'LMS', '2025-07-15');
INSERT INTO uda.comm_code
(COM_CD_ID, COM_CD, COM_CD_NM, COM_CD_EN, SORT_SN, VBG_CRE_USER, VBG_CRE_DTM)
VALUES('00001', '3', '날짜', 'DATE', 3, 'LMS', '2025-07-15');
INSERT INTO uda.comm_code
(COM_CD_ID, COM_CD, COM_CD_NM, COM_CD_EN, SORT_SN, VBG_CRE_USER, VBG_CRE_DTM)
VALUES('00001', '4', '일시', 'DATE', 4, 'LMS', '2025-07-15');
INSERT INTO uda.comm_code
(COM_CD_ID, COM_CD, COM_CD_NM, COM_CD_EN, SORT_SN, VBG_CRE_USER, VBG_CRE_DTM)
VALUES('00001', '5', '체크박스', 'check', 5, 'LMS', '2025-07-15');

INSERT INTO uda.std_main (TABLE_NAME, TABLE_ID, VBG_CRE_USER, VBG_CRE_DTM) values
('Artist Album list', 'uda_db_001', '이민수', '2025-07-10'),
('sw 통합결재', 'uda_db_002', '김정욱', '2025-07-11'),
('회의실 현황', 'uda_db_003', '문재선', '2025-07-12'),
('금속재료조회', 'uda_db_004', '김진한', '2025-07-13'),
('배출가스', 'uda_db_005', '한은영', '2025-07-14'),
('테스트', 'uda_db_006', '홍민기', '2025-07-15')
